version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "courses"
      POSTGRES_USER: "danzelVash"
      POSTGRES_PASSWORD: "22332223"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"


#  app:
#    build: "."
#    ports:
#      - "8080"
#    depends_on:
#      - postgres
#    environment:
#      db_host: postgres
#    volumes:
#      - ./logs:/app/logs



#  nginx:
#    build: "./nginx"
#    ports:
#      - "80:80"
#    depends_on:
#      - app
#    volumes:
#      - ./templates/css:/app/static/css
#      - ./templates/img:/app/static/img
#      - ./templates/js:/app/static/js